apiVersion: v1
kind: Service
metadata:
  name: passly-frontend-service
  namespace: passly
spec:
  selector:
    app: passly-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
  type: ClusterIP
