# rename secret.yaml to secret.yml and fill the variables
apiVersion: v1
kind: Secret
metadata:
  name: passly-backend-secret
  namespace: passly
type: Opaque
stringData:
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  MONGODB_URL: ""
  JWT_KEY: ""
